[package]
name = "input-embedding"
version = "0.1.0"
edition = "2021"
default-run = "input-embedding"

[features]
default = ["std"]
std = ["raster/std"]
profiling = ["raster/profiling"]

[dependencies]
raster = { path = "../../../raster/crates/raster", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
